def get_circle_colors():
    colors_dict = {
        'Activitées sportives': '#0082C3',
        'Administratif': '#000000',
        'Artisans': '#8B4513',
        'Bien être': '#FFB6C1',
        'Boulangerie': '#f2bf95',
        'Bus': '#db281d',
        'Cathedral': '#FFA500',
        'Collège & Lycée': '#DDA0DD',
        'Culture & Spectacle': '#FFA500',
        'Divertissement': '#FFA500',
        'Eglises': '#FFFFF0',
        'Études supérieures': '#DDA0DD',
        'Hotel': '#D2691E',
        'Marché': '#8B4513',
        'Metro': '#db281d',
        'monument historique': '#D3D3D3',
        'Mosqué': '#FFFFF0',
        'Parc': '#9ACD32',
        'Petite enfance': '#DDA0DD',
        'Restaurant': '#00FFFF',
        'Santé': '#00FF00',
        'Service Public': '#0000CD',
        'Shopping': '#708090',
        'Supermarché & pharmacie': '#FFFFFF',
        'Tribunal': '#000000',
        'Vélo': '#7CFC00',
        'Vie festive': '#FFD700'
    }

    return colors_dict

def get_type_local(type_local):
    code_type_local = {
                        'Tous' : 0,
                        'Maisons' : 1.0,
                        'Appartements':2.0
                        }
    return code_type_local[type_local]

def get_cat_dict():
    dict_cat = {'Activitées sportives': ['fitness_centre',
            'sports',
            'sports_centre',
            'sports_hall',
            'swimming_pool'],
            'Administratif': ['government', 'Departement', 'Mairie'],
            'Artisans': ['butcher',
            'cheese',
            'chocolate',
            'deli',
            'florist',
            'greengrocer',
            'hairdresser',
            'pastry',
            'seafood',
            'wine'],
            'Bien être': ['beauty'],
            'Boulangerie': ['bakery'],
            'Bus': ['platform'],
            'Cathedral': ['cathedral'],
            'Collège & Lycée': ['College', 'Lycée'],
            'Culture & Spectacle': ['arts_centre',
            'music_school',
            'community_centre',
            'library',
            'museum',
            'theatre',
            'zoo'],
            'Divertissement': ['cinema'],
            'Eglises': ['church'],
            'Études supérieures': ['University'],
            'Hotel': ['hotel'],
            'Marché': ['marketplace'],
            'Metro': ['station'],
            'monument historique': ['attraction'],
            'Mosqué': ['mosque'],
            'Parc': ['park'],
            'Petite enfance': ['Crèche', 'Maternelle', 'Primaire', 'playground'],
            'Restaurant': ['fast_food', 'food_court', 'restaurant'],
            'Santé': ['dentist', 'doctors', 'hospital', 'laboratory'],
            'Service Public': ['Décheterie',
            'public',
            'Pompier',
            'police',
            'post_office'],
            'Shopping': ['alcohol',
            'optician',
            'antiques',
            'books',
            'clothes',
            'cosmetics',
            'fashion_accessories',
            'interior_decoration',
            'jewelry',
            'mall',
            'music',
            'musical_instrument',
            'perfumery',
            'retail',
            'shoes',
            'tea',
            'travel_agency',
            'watches'],
            'Supermarché & pharmacie': ['pharmacy', 'supermarket'],
            'Tribunal': ['Tribunal'],
            'Vélo': ['bicycle_parking', 'bicycle_rental'],
            'Vie festive': ['tobacco', 'bar', 'cafe', 'casino', 'nightclub', 'pub']}
    return dict_cat
